### PR TITLE
Fix find command bug: Find command allows empty search after prefix

### LINKED ISSUE #235: Find command allows empty search after prefix
Find command dosent throw an error if value after prefix is empty

Screenshot 2024-10-31 at 12 20 14 PM
Screenshot 2024-10-31 at 12 20 09 PM

### PR DESCRIPTION
**Pull request by hooyushing**
Fixes #235

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/FindCommandParser.java [hunk 1]
```diff
@@ -37,25 +37,88 @@ public FindCommand parse(String args) throws ParseException {
...
+
+        if (isMonthPaidPresent && !isNamePresent && !isClassIdPresent && !isNotMonthPaidPresent) {
+            return FindCommandType.MONTHPAID;
+        } else if (isNamePresent && isClassIdPresent && !isMonthPaidPresent && !isNotMonthPaidPresent) {
+            return FindCommandType.NAMEANDCLASSID;
+        } else if (isNamePresent && !isClassIdPresent && !isMonthPaidPresent && !isNotMonthPaidPresent) {
+            return FindCommandType.NAME;
+        } else if (!isNamePresent && isClassIdPresent && !isMonthPaidPresent && !isNotMonthPaidPresent) {
+            return FindCommandType.CLASSID;
+        } else if (isNotMonthPaidPresent && !isNamePresent && !isClassIdPresent && !isMonthPaidPresent) {
```
Comment (sumomomomomo) [inline src/main/java/seedu/address/logic/parser/FindCommandParser.java:73]:
```suggestion
        } else if (!isNamePresent && !isClassIdPresent && !isMonthPaidPresent && isNotMonthPaidPresent) {
```

**Review by sumomomomomo — COMMENTED** [review]
LGTM
